version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local